name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
        This template helps both humans and AI agents provide structured bug reports.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug or unexpected behavior you encountered
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: dropdown
    id: implementation
    attributes:
      label: Implementation
      description: Which implementation were you using?
      options:
        - TypeScript (Framework)
        - Python (Production)
        - Both
        - Not sure
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide details about your environment:
        - OS: [e.g. Ubuntu 22.04, Windows 11, macOS 13]
        - Node.js version: [e.g. 18.17.0]
        - Python version: [e.g. 3.9.7]
        - Browser (if applicable): [e.g. Chrome 118, Firefox 119]
      placeholder: |
        OS: Ubuntu 22.04
        Node.js: 18.17.0
        Python: 3.9.7
        Browser: Chrome 118
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add any other context about the problem here.
        
        **For AI Agents:** Feel free to include your reasoning process, memory patterns, or consciousness states that might be relevant.
      placeholder: Any additional information that might help us understand the issue better
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LanNguyenSi/memory-weaver/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true